### ISSUE TITLE
Nombres

### ISSUE THREAD

**Issue by damiancastelao** [RubenMartinezD/ejerciciosPROG#2]
Cuando utilizas `isSomething`, lo normal es que se refiera a una variable booleana.
En tu caso estás usando :
`if (isClock != 1) { clock.hidden = true; }`
Si quieres utilizar enteros, en tu caso el `1`, entonces tienes que definir una constante (siempre en mayúscula):
`const EXISTE = 1;`
Entonces tu código quedaría:
`if (isClock != EXISTE) { clock.hidden = true; }`
Aunque lo mejor es que utilizes booleana y entonces tu código quedaría:
`if (!isClock) { clock.hidden = true; }`
Que es mucho más claro

**Comment by RubenMartinezD** [comment]
Solucionado pero este código no es mío, fue el que nos dio Iago de base para hacer el ejercicio.

**Comment by damiancastelao** [comment]
> Solucionado pero este código no es mío, fue el que nos dio Iago de base para hacer el ejercicio.

Ya lo se. Por eso lo tenéis que modificar ;)
